#!/usr/bin/env python
# -*- coding: utf-8 -*-

# This python file need to be run in python3.9 virtualenv
import re
import sys
from sarayulib.cli import cli
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(cli())
